name: spark-processing

on:
  repository_dispatch:
    types: [spark]

jobs:
  spark:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin

      - name: Configurar Apache Spark
        uses: vemonet/setup-spark@v1
        with:
          spark-version: "3.5.3"
          hadoop-version: "3"

      - name: Verificar instalación de Spark
        run: spark-submit --version

      - name: Descargar dataset
        run: wget -O dataset.csv ${{ github.event.client_payload.dataseturl }}

      - name: Descargar código Python
        run: wget -O data.py ${{ github.event.client_payload.codeurl }}

      - name: Ejecutar análisis con Spark
        run: spark-submit --master local data.py dataset.csv

      - name: Verificar resultados
        run: ls -la results

      - name: Hacer commit de resultados
        env:
          CI_COMMIT_MESSAGE: "Guardar resultados de Spark"
          CI_COMMIT_AUTHOR: "harlock024"
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "hadith024@gmail.com"
          git add results
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
